FROM python:3.12.14-slim-trixie

WORKDIR /backend

COPY backend/workeringestion/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/workeringestion/ ./workeringestion/

CMD ["python", "-m", "workeringestion.main"]
