FROM python:3.12.14-slim-trixie

WORKDIR /backend

COPY backend/core/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/core/ ./core/

EXPOSE 8000

CMD ["uvicorn", "core.main:app", "--host", "0.0.0.0", "--port", "8000"]
