services:
  backend:
    build:
      context: .
      dockerfile: backend/core/Dockerfile
    networks:
      - enervision_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    secrets:
      - db_password
      - keycloak_client_secret

  frontend:
    build:
      context: ./frontend
    networks:
      - enervision_network
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: ${BACKEND_URL}
    volumes:
      - ./frontend/.streamlit/secrets.toml:/frontend/.streamlit/secrets.toml:ro

  worker-ingestion:
    build:
      context: .
      dockerfile: backend/workeringestion/Dockerfile
    networks:
      - enervision_network
    environment:
      MOCK_API_URL: ${MOCK_API_URL}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME}
      AZURE_SAS_INGESTION: ${AZURE_SAS_INGESTION}

  health:
    build:
      context: .
      dockerfile: backend/health/Dockerfile
    networks:
      - enervision_network
    ports:
      - "8002:8000"
  etl:
    networks:
      - enervision_network
    build:
      context: .
      dockerfile: backend/etl/Dockerfile

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PWD: ${POSTGRES_APP_PWD}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME}
      AZURE_SAS_ETL: ${AZURE_SAS_ETL}

    volumes:
      - ./backend/etl:/backend/etl

    command: python -m etl.main

secrets:
  db_password:
    file: ./secrets/db_password

  keycloak_client_secret:
    file: ./secrets/keycloak_client_secret

networks:
  enervision_network:
    external: true
