services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    cap_add:
      - NET_BIND_SERVICE
    command:
      - --entrypoints.websecure.address=:443
      - --providers.file.filename=/etc/traefik/dynamic.yml
    ports:
      - 443:443
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs:ro
  backend:
    networks:
      - enervision_network
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/backend/backend

    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PWD: ${POSTGRES_APP_PWD}

  worker-ingestion:
    build:
      context: .
      dockerfile: backend/workerIngestion/Dockerfile

    ports:
      - "8001:8000"

    environment:
      MOCK_API_URL: http://10.105.200.45:8000
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_STORAGE_CONTAINER_NAME: ${AZURE_STORAGE_CONTAINER_NAME}
      AZURE_SAS_INGESTION: ${AZURE_SAS_INGESTION}

    volumes:
      - ./backend/__init__.py:/backend/backend/__init__.py
      - ./backend/core:/backend/backend/core
      - ./backend/workerIngestion:/backend/backend/workerIngestion

    command: uvicorn backend.workerIngestion.main:app --host 0.0.0.0 --port 8000 --reload

secrets:
  db_password:
    file: ./secrets/db_password

  keycloak_client_secret:
    file: ./secrets/keycloak_client_secret

networks:
  enervision_network:
    external: true