sonar.organization=enervisiong3
sonar.projectKey=EnervisionG3_EnerVisionApplicatif

sonar.sources=backend,frontend,authentication
sonar.tests=backend/core/tests,backend/etl/tests,backend/health/tests,backend/prediction/tests,backend/workeringestion/tests,frontend/tests

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage-reports/**/coverage.xml

sonar.coverage.exclusions=**/scripts/**,**/tests/**,frontend/app.py,frontend/pages/**,frontend/components/**

sonar.exclusions=**/__pycache__/**,.venv/**,data/**,mlruns/**,mlflow/**,certs/**,secrets/**,frontend/assets/**,**/*.md

sonar.qualitygate.wait=true
